function [fitresult, gof] = brakeFeedforward(speed, acceleration, brake1)
%CREATEFIT(SPEED,ACCELERATION,BRAKE1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : acceleration
%      Z Output: brake1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Oct-2019 21:58:18


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, acceleration, brake1 );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface Fit', 'Empirical Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Velocity (m/s)', 'Interpreter', 'none' );
ylabel( 'Longitudinal Acceleraion (m/s^{2})');
zlabel( 'Brake', 'Interpreter', 'none' );
grid on

zlim([-1 0])


