function [fitresult, gof] = combined_inverse(speed, acceleration, input1)
%CREATEFIT(SPEED,ACCELERATION,INPUT1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : acceleration
%      Z Output: input1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Oct-2019 14:21:58


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, acceleration, input1 );

% Set up fittype and options.
ft = fittype( 'poly33' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [0 -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf 0];
opts.Upper = [0 Inf Inf Inf Inf Inf Inf Inf Inf 0];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface Fit', 'Empirical Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Velocity (m/s)', 'Interpreter', 'none' );
ylabel( 'Longitudinal Accleration (m/s^{2})');
zlabel( 'Input', 'Interpreter', 'none' );
grid on

zlim([-1.0 1.0])


