function [fitresult, gof] = createFit(speed, throttle, acceleration)
%CREATEFIT(SPEED,THROTTLE,ACCELERATION)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : throttle
%      Z Output: acceleration
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Aug-2019 12:13:51


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, throttle, acceleration );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Throttle Speed-Based Acceleration Map' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Mapping', 'acceleration vs. speed, throttle', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'speed (m/s)', 'Interpreter', 'none' );
ylabel( 'throttle (%)', 'Interpreter', 'none' );
zlabel( 'acceleration (m/s^2)', 'Interpreter', 'none' );
grid on
view( 2.5, 60.3 );


