function [fitresult, gof] = lateralDynamics(speed, road_wheel_angles_rad, lateral_acceleration)
%CREATEFIT(SPEED,ROAD_WHEEL_ANGLES_RAD,LATERAL_ACCELERATION)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : road_wheel_angles_rad
%      Z Output: lateral_acceleration
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Sep-2019 21:34:07


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, road_wheel_angles_rad, lateral_acceleration );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Data-Driven Lateral Dynamics' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface Fit', 'Emperical Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Velocity (m/s)', 'Interpreter', 'none' );
ylabel( 'Road Wheel Angle (rad)', 'Interpreter', 'none' );
zlabel( 'Lateral Acceleration (m/s^{2})');
% Title
% title('Data-Driven Lateral Dynamics')
grid on


