function [fitresult, gof] = lateralVelocity(speed, road_wheel_angles_rad, lateral_velocity)
%CREATEFIT(SPEED,ROAD_WHEEL_ANGLES_DEG,LATERAL_VELOCITY)
%  Create a fit.
%
%  Data for 'Surface Fit' fit:
%      X Input : speed
%      Y Input : road_wheel_angles_deg
%      Z Output: lateral_velocity
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Sep-2019 22:27:53


%% Fit: 'Surface Fit'.
[xData, yData, zData] = prepareSurfaceData( speed, road_wheel_angles_rad, lateral_velocity );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Surface Fit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface Fit', 'Empirical Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Velocity (m/s)', 'Interpreter', 'none' );
ylabel( 'Road Wheel Angle (rad)', 'Interpreter', 'none' );
zlabel( 'Angular Velocity (rad/s)', 'Interpreter', 'none' );

% title
% title('Data-Driven Lateral Velocity Fit')
grid on


