function [fitresult, gof] = psidot_inverse(speed, lateral_velocity, road_wheel_angles_rad)
%CREATEFIT(SPEED,LATERAL_VELOCITY,ROAD_WHEEL_ANGLES_RAD)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : lateral_velocity
%      Z Output: road_wheel_angles_rad
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Oct-2019 10:40:05


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, lateral_velocity, road_wheel_angles_rad );

% Set up fittype and options.
ft = fittype( 'poly33' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [0 -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf -Inf];
opts.Upper = [0 Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'road_wheel_angles_rad vs. speed, lateral_velocity', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'speed', 'Interpreter', 'none' );
ylabel( 'lateral_velocity', 'Interpreter', 'none' );
zlabel( 'road_wheel_angles_rad', 'Interpreter', 'none' );
grid on
view( -37.7, 38.9 );


