function [fitresult, gof] = throttleDynamics(speed, throttle1, acceleration)
%CREATEFIT1(SPEED,THROTTLE1,ACCELERATION)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : speed
%      Y Input : throttle1
%      Z Output: acceleration
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Sep-2019 09:31:49


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( speed, throttle1, acceleration );

% Set up fittype and options.
ft = fittype( 'poly33' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Plot fit with data.
figure( 'Name', 'Throttle' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Surface Fit', 'Emperical Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Velocity (m/s)', 'Interpreter', 'none' );
ylabel( 'Throttle %', 'Interpreter', 'none' );
zlabel( 'Longitdunal Acceleration (m/s^{2})');

% Title
% title('Data-Driven Throttle Longitudinal Dynamics')
grid on


