#!/usr/bin/env bash
rostopic pub -r 30 /pacmod/as_rx/brake_cmd pacmod_msgs/SystemCmdFloat "header:
  seq: 0
  stamp: {secs: 0, nsecs: 0}
  frame_id: ''
enable: true
ignore_overrides: false
clear_override: false
clear_faults: false
command: 0.1" 
 
